### PR TITLE
Addition of Dell TSFM-IR01

### PR DESCRIPTION
**Pull request by sealldeveloper**
I'm unsure what the two squares do on the model I cloned so I labelled them `SquareUp` and `SquareDown`. If anyone knows what it does they can update it with an issue or pull request.

### CODE REVIEW

**Comment by darmiel** [comment]
I think they represent `Keystone adjustment down` and `Keystone adjustment up` which allows you to correct the trapezoidal distortion of the projected image - according to [this manual](https://www.projectorcentral.com/pdf/projector_manual_5482.pdf)

**Comment by sealldeveloper** [comment]
Good find, i'll update it right now.

**Comment by darmiel** [comment]
I think the name is a bit too long to be displayed at the Flipper. At least the `Up`/`Down` would be chopped off.
What do you think about `Keystone+` and `Keystone-` - would that be descriptive enough?

**Comment by sealldeveloper** [comment]
Sounds good, updating.

**Pull request merged**
