### PR TITLE
(Fixed) IR Additions

### PR DESCRIPTION
**Pull request by emptythevoid**
The only thing I would like to ignore with the linter, if possible, is for the GPX_D2816.ir file.  The remote actually has printed "Prev" and "Next."  I can change them, if you'd prefer, but I thought I'd explain first.

Otherwise, I think everything else is fixed.

### CODE REVIEW

**Comment by darmiel** [comment]
Thank you for your additions and for fixing the previous issues 🙂

The linter only complains about the names because they occur twice (2x Prev, 2x Next), which can lead to confusion. 
Is it possible that the duplicates are `Fast Forward/Backward` ? On a picture of the remote I saw the following buttons:

image

But if you say it's correct as it is now, that's okay too and I can go ahead and merge it as it currently is.

**Comment by emptythevoid** [comment]
I can't do a good job explaining, except I think I tried to fix it from the linter, decided against it, and un-fixed the wrong thing. Does it look OK now?

**Comment by emptythevoid** [comment]
(And thank you for helping me.  I'm not used to using a proper github workflow with others)

**Review by darmiel — APPROVED** [review]

**Comment by darmiel** [comment]
Yes, looks good now 👍

**Comment by emptythevoid** [comment]
Thank you very much!

**Pull request merged**
