### PR TITLE
Update buttons to naming scheme

### PR DESCRIPTION
**Pull request by jaroslavmraz**
Change buttons like Power, Mute Volume_UP to naming scheme POWER VOL+ ...

### CODE REVIEW

**Comment by UberGuidoZ** [comment]
This is fantastic! Thank you for the work. I did notice a few during spot checks that seem to be incorrect. Example:

Name: On -> POWER

After the rename, it was lacking the `Name:` identifier. (See [example 1](https://github.com/logickworkshop/Flipper-IRDB/pull/191/files#diff-2bf939e19076b4e096bd56a0a8345d4a6312453d950b9678607b65b11d385bdc) and [example 2](https://github.com/logickworkshop/Flipper-IRDB/pull/191/files#diff-14f9ef119ef1cf825e41280fc9b4601abf086668ee3c44df55812f7c7bd2cc31) - there may be more.)

Could you please verify and correct these small errors? I would love to get this merged in. <3

**Comment by jaroslavmraz** [comment]
Oh. That hapends? Ok I will fix it.

**Comment by jaroslavmraz** [comment]
Check this shoud do the job. I had used manual rename before and thats the problem. After I had use Regex to comapre strings. So i used Regex to fix it it was 256 records.

**Comment by UberGuidoZ** [comment]
Wonderful! Looks much better now. Will get this merged - thanks for all your additions! Will get you added to the ReadMe (well deserved.)

**Pull request merged**
